### ISSUE TITLE
Compiler warning unused function "finterp"

### ISSUE THREAD

**Issue by IboKhaled** [ardnew/ILI9341-STM32-HAL#3]
The function `finterp` (ili9341.c line 628) is defined but not used.
Is there a reason for it to exist or can it be removed?

**Comment by ardnew** [comment]
I'm guessing I used it at some point for blending colors or interpolating coordinates, but if you can verify it's not being used, it can certainly be removed. 

Nothing special about it from any other linear interpolation (except it uses floats as opposed to scaled integers)
